version: '3.9'

services:
  rabbitmq:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    ports:
      - ${PORT}
      - ${PORT_GUI}
    volumes:
      - broker_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=BROKER_USER
      - RABBITMQ_DEFAULT_PASS=qu3u3r
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  broker_data: