version: '3.9'

services:
  wiremock:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    ports:
      - ${PORT}
      - ${PORT_APIS}
    volumes:
      - wiremock_data:/home/wiremock
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  wiremock_data: